---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Cell In[5], line 5
      2 set_name = deploy_set.split('/')[-2]
      4 # Read image and GT
----> 5 img_name, folder_name, img_size = get_maximum_img_size_and_names(deploy_set)
      7 mkdir(output_dir + '/'+ set_name + '/')
      8 mkdir(output_dir + '/' + set_name + '/mnt_results/')

File ~\Pictures\vamsi\CoarseNet\CoarseNet_utils.py:381, in get_maximum_img_size_and_names(dataset, sample_rate, max_size)
    378     img_name.extend(img_name_t.tolist()*rate)
    379     folder_name.extend([folder]*img_name_t.shape[0]*rate)
--> 381     img_size.append(np.array(imread(folder + 'img_files/' + img_name_t[0] + '.bmp', mode='L').shape))
    383 img_name = np.asarray(img_name)
    384 folder_name = np.asarray(folder_name)

IndexError: index 0 is out of bounds for axis 0 with size 0
